[book]
title = "Bagua Tutorials"
description = "Guide on how to use Bagua, a deep learning distributed training framework"
author = "Kuaishou AI Platform & DS3 Lab <admin@mail.xrlian.com>"

[output.linkcheck]
