# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: install
          args: --git https://github.com/MatheusRich/mdBook.git mdbook
      - uses: actions-rs/cargo@v1
        with:
          command: install
          args: mdbook-linkcheck
      - uses: actions-rs/cargo@v1
        with:
          command: install
          args: mdbook-open-on-gh
      - run: mdbook test
      - run: mdbook build

  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: install
          args: --git https://github.com/MatheusRich/mdBook.git mdbook
      - uses: actions-rs/cargo@v1
        with:
          command: install
          args: mdbook-linkcheck
      - uses: actions-rs/cargo@v1
        with:
          command: install
          args: mdbook-open-on-gh
      - run: mdbook build
      - run: ./ci/deploy.sh
