# This is a basic workflow to help you get started with Actions

name: tutorials

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: ikzk/bagua-ci:latest
    steps:
      - uses: actions/checkout@v2
      - run: rustup default stable
      - run: mdbook test
      - run: mdbook build

  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    container: ikzk/bagua-ci:latest
    steps:
      - uses: actions/checkout@v2
      - run: rustup default stable
      - run: mdbook build
      - run: ./ci/deploy.sh
